// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using platform_role_core_func.Migrations;

namespace platform_role_core_func.Migrations.Migrations
{
    [DbContext(typeof(MigrationDataContext))]
    [Migration("20211005132542_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Elements2.RbacService.Model.DbModel.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("Elements2.RbacService.Model.DbModel.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Resource")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Elements2.RbacService.Model.DbModel.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Elements2.RbacService.Model.DbModel.TenantUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "TenantId");

                    b.ToTable("TenantUsers");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("PermissionTenantUser", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantUsersUserId")
                        .HasColumnType("text");

                    b.Property<string>("TenantUsersTenantId")
                        .HasColumnType("text");

                    b.HasKey("PermissionsId", "TenantUsersUserId", "TenantUsersTenantId");

                    b.HasIndex("TenantUsersUserId", "TenantUsersTenantId");

                    b.ToTable("PermissionTenantUser");
                });

            modelBuilder.Entity("RoleTenantUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantUsersUserId")
                        .HasColumnType("text");

                    b.Property<string>("TenantUsersTenantId")
                        .HasColumnType("text");

                    b.HasKey("RolesId", "TenantUsersUserId", "TenantUsersTenantId");

                    b.HasIndex("TenantUsersUserId", "TenantUsersTenantId");

                    b.ToTable("RoleTenantUser");
                });

            modelBuilder.Entity("Elements2.RbacService.Model.DbModel.ApplicationRole", b =>
                {
                    b.HasBaseType("Elements2.RbacService.Model.DbModel.Role");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationRole");
                });

            modelBuilder.Entity("Elements2.RbacService.Model.DbModel.TenantRole", b =>
                {
                    b.HasBaseType("Elements2.RbacService.Model.DbModel.Role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ToTable("TenantRole");
                });

            modelBuilder.Entity("Elements2.RbacService.Model.DbModel.Permission", b =>
                {
                    b.HasOne("Elements2.RbacService.Model.DbModel.Application", "Application")
                        .WithMany("Permissions")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Elements2.RbacService.Model.DbModel.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elements2.RbacService.Model.DbModel.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionTenantUser", b =>
                {
                    b.HasOne("Elements2.RbacService.Model.DbModel.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elements2.RbacService.Model.DbModel.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("TenantUsersUserId", "TenantUsersTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleTenantUser", b =>
                {
                    b.HasOne("Elements2.RbacService.Model.DbModel.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elements2.RbacService.Model.DbModel.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("TenantUsersUserId", "TenantUsersTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elements2.RbacService.Model.DbModel.ApplicationRole", b =>
                {
                    b.HasOne("Elements2.RbacService.Model.DbModel.Application", "Application")
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("Elements2.RbacService.Model.DbModel.Role", null)
                        .WithOne()
                        .HasForeignKey("Elements2.RbacService.Model.DbModel.ApplicationRole", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Elements2.RbacService.Model.DbModel.TenantRole", b =>
                {
                    b.HasOne("Elements2.RbacService.Model.DbModel.Role", null)
                        .WithOne()
                        .HasForeignKey("Elements2.RbacService.Model.DbModel.TenantRole", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elements2.RbacService.Model.DbModel.Application", b =>
                {
                    b.Navigation("ApplicationRoles");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
